name: SPFx CI/CD Pipeline
on:
  push:
    branches:
      - main  # Trigger on push to main branch

env:
  SPPKG_FILE_NAME: 'ci-cd-demo.sppkg'
  SEND_MAIL: 'true'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Setup Node.js
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # 3. Install dependencies
    - name: Install npm dependencies
      run: npm ci

    # 4. Bundle and package SPFx
    - name: Bundle and package SPFx
      run: |
        gulp bundle --ship
        gulp package-solution --ship

    # 4a. Validate SPFx package file
    - name: Validate SPFx package file
      run: |
        FILE_PATH="sharepoint/solution/${{ env.SPPKG_FILE_NAME }}"
        if [ ! -f "$FILE_PATH" ]; then
          echo "ERROR: SPFx package file not found at $FILE_PATH"
          exit 1
        fi
        FILE_SIZE=$(stat -c%s "$FILE_PATH")
        if [ "$FILE_SIZE" -eq 0 ]; then
          echo "ERROR: SPFx package file is empty"
          exit 1
        fi
        echo "SPFx package file exists and is valid: $FILE_PATH (size: $FILE_SIZE bytes)"

    # 5. Login to SharePoint Online using certificate
    - name: Microsoft 365 CLI Login (Certificate)
      uses: pnp/action-cli-login@v3
      with:
        TENANT: ${{ secrets.TENANT_ID }}
        APP_ID: ${{ secrets.APP_ID }}
        CERTIFICATE_ENCODED: ${{ secrets.CERTIFICATE_BASE64 }}
        CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}


    # 6. Deploy SPFx package to site collection app catalog
    - name: Deploy SPFx package (debug)
      run: |
        m365 spo app add --filePath sharepoint/solution/ci-cd-demo.sppkg --scope sitecollection \ --appCatalogUrl "https://t12y7.sharepoint.com/sites/MySite_Swayam" --overwrite --debug


    # 7. Optional: Send email notification
    - name: Send email notification
      if: env.SEND_MAIL == 'true'
      run: |
        m365 spo mail send --webUrl "https://t12y7.sharepoint.com/sites/MySite_Swayam" --to 'swayamhpatel@outlook.com' --subject 'SPFx Deployment Success' --body 'New sppkg has been deployed to App Catalog.'
