name: SPFx CICD with Office 365 CLI Ubuntu
on: push
# any branch can be specified

env:
  SPPKG_FILE_NAME: 'cicddemo.sppkg'
  SEND_MAIL: 'true'

jobs: 

  built-and-deploy:

    runs-on: ubuntu-latest

    steps:

    #checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    #Setup node.js runtime
    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    #npm install
    - name: Install dependecies
      run: npm ci

    #gulp bundle and package solution
    - name: Bundle and package
      run: |
        gulp bundle --ship
        gulp package-solution --ship

    # Login to tenant using action-cli-login
    - name: Microsoft 365 CLI Login
      uses: pnp/action-cli-login@v2.0.0
      with:
        ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    # Deploy package to tenant using action-cli-deploy
    - name: Microsoft 365 CLI Deploy
      uses: pnp/action-cli-deploy@v2.0.0
      id: deploy
      with:
        APP_FILE_PATH: sharepoint/solution/${{ env.SPPKG_FILE_NAME }}
        SKIP_FEATURE_DEPLOYEMENT: true
        OVERWRITE: true

    # print app id
    - name: Get the App_ID
      run: echo "The App_Id is ${{ steps.deploy.outputs.APP_ID }}"

    # send an email using action-cli-runscript
    - name: Microsoft 365 CLI Send email
      uses: pnp/action-cli-runscript@v2.0.0
      with:
        CLI_MICROSOFT365_SCRIPT: m365 spo mail send --webUrl https://t12y7.sharepoint.com/sites/MySite_Swayam --to 'swayamhpatel@outlook.com'  --subject 'New Deploymnet succeed' --body 'new sppkg is deployed to appcatalog.'
      if: env.SEND_MAIL == 'true'






        
