name: SPFx CI/CD Pipeline
on:
  push:
    branches:
      - main  # Trigger on push to main branch

env:
  SPPKG_FILE_NAME: 'cicddemo.sppkg'
  APP_CATALOG_URL: 'https://t12y7.sharepoint.com/sites/MySite_Swayam/appCatalog'
  SEND_MAIL: 'true'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Setup Node.js
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # 3. Install dependencies
    - name: Install npm dependencies
      run: npm ci

    # 4. Bundle and package SPFx
    - name: Bundle and package SPFx
      run: |
        gulp bundle --ship
        gulp package-solution --ship

    # 5. Login to SharePoint Online using certificate
    - name: Microsoft 365 CLI Login (Certificate)
      uses: pnp/action-cli-login@v2.0.0
      with:
        AUTH_TYPE: certificate
        APP_ID: ${{ secrets.APP_ID }}
        TENANT: ${{ secrets.TENANT_ID }}
        CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
        # optional but recommended
        DEBUG: true
        
    # 6. Deploy SPFx package
    - name: Deploy SPFx package
      uses: pnp/action-cli-deploy@v2.0.0
      with:
        APP_FILE_PATH: sharepoint/solution/${{ env.SPPKG_FILE_NAME }}
        APP_CATALOG_SCOPE: sitecollection
        APP_CATALOG_URL: ${{ secrets.APP_CATALOG_URL }}
        SKIP_FEATURE_DEPLOYEMENT: true
        OVERWRITE: true

    # 7. Optional: Send email notification
    - name: Send email notification
      if: env.SEND_MAIL == 'true'
      uses: pnp/action-cli-runscript@v2.0.0
      with:
        CLI_MICROSOFT365_SCRIPT: |
          m365 spo mail send --webUrl ${{ secrets.APP_CATALOG_URL }} --to 'swayamhpatel@outlook.com' --subject 'SPFx Deployment Success' --body 'New sppkg has been deployed to App Catalog.'
