name: SPFx CI/CD with PnP PowerShell
on:
  push:
    branches:
      - main   # or any branch you want

env:
  SPPKG_FILE_NAME: 'cicddemo.sppkg'
  APP_CATALOG_URL: 'https://t12y7.sharepoint.com/sites/MySite_Swayam/AppCatalog'
  SEND_MAIL: 'true'

jobs:
  build-and-deploy:
    runs-on: windows-latest   # PnP PowerShell works best on Windows runner
    steps:

    # 1. Checkout repository
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Setup Node.js
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # 3. Install dependencies
    - name: Install npm dependencies
      run: npm ci

    # 4. Bundle and package SPFx solution
    - name: Bundle and package SPFx
      run: |
        gulp bundle --ship
        gulp package-solution --ship

    # 5. Install PnP PowerShell module
    - name: Install PnP PowerShell
      run: Install-Module -Name PnP.PowerShell -Force -Scope CurrentUser

    # 6. Connect to SharePoint Online
    - name: Connect to SharePoint
      run: |
        $pass = ConvertTo-SecureString "${{ secrets.ADMIN_PASSWORD }}" -AsPlainText -Force
        $cred = New-Object System.Management.Automation.PSCredential("${{ secrets.ADMIN_USERNAME }}", $pass)
        Connect-PnPOnline -Url $env:APP_CATALOG_URL -Credentials $cred

    # 7. Upload and deploy the SPFx package
    - name: Deploy SPFx package
      run: |
        Add-PnPApp -Path "sharepoint/solution/${{ env.SPPKG_FILE_NAME }}" -Overwrite
        Publish-PnPApp -Identity ${{ env.SPPKG_FILE_NAME }}

    # 8. Optional: Send an email notification
    - name: Send Email Notification
      if: env.SEND_MAIL == 'true'
      run: |
        $pass = ConvertTo-SecureString "${{ secrets.SP_PASS }}" -AsPlainText -Force
        $cred = New-Object System.Management.Automation.PSCredential("${{ secrets.SP_USER }}", $pass)
        Connect-PnPOnline -Url "https://t12y7.sharepoint.com/sites/MySite_Swayam" -Credentials $cred
        Send-PnPMail -To "swayamhpatel@outlook.com" -Subject "SPFx Deployment Completed" -Body "New SPFx package deployed successfully."
